services:
  immich:
    image: ghcr.io/immich-app/immich-server:latest
    container_name: immich
    restart: unless-stopped
    volumes:
      - /mnt/drive/photos:/usr/src/app/upload
      - /home/server/containers/immich:/config
    ports:
      - "2283:2283"

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - /mnt/drive/movies:/media/movies
      - /mnt/drive/shows:/media/shows
      - /home/server/containers/jellyfin:/config
    ports:
      - "8096:8096"

  emby:
    image: emby/embyserver
    container_name: emby
    restart: unless-stopped
    volumes:
      - /mnt/drive/movies:/mnt/movies
      - /mnt/drive/shows:/mnt/shows
      - /home/server/containers/emby:/config
    ports:
      - "8097:8096"
